import './globals.css'
import type{  ReactNode } from 'react'
import { fontSans, fontMono } from '@/lib/fonts'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
        <body className={cn("bg-background min-h-svh font-sans antialiased", fontSans.variable, fontMono.variable)}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
